### PR TITLE
Updated according to the Support library 22.1.0

### PR DESCRIPTION
**Pull request by kevindesai777**
ActionBarActivity is now deprecated.

### CODE REVIEW

**Comment by kanytu** [comment]
I will have to check this because if the user hasn't installed the support library yet this will not compile. A new api check will have to be created. This will not be approved most likely. Will check it later

**Comment by kanytu** [comment]
This will be harder than I thought.

I'm using this line to include the support library:

```
<dependency mavenUrl="com.android.support:support-v4:${targetApi}.+"/>
```

Since I'm using "+" I have no way to check if the user has already installed the latest support version with that deprecation.

I will keep investigation and I hope to find a solution to this. In the meanwhile I can't merge this PR since it can break compatibility. Thanks for your support any way :)

EDIT: What I think it's impossible because there is no way to know what support has been installed without running gradle build :/

**Comment by kanytu** [comment]
In case someone wants to help, this project is built using FreeMaker syntax since it's the one Google is using for their templates:

More info
http://freemarker.org/docs/dgui_template_exp.html

It's implemetation takes place at: android_studio_folder/plugins/android/lib/android.jar -> package com.android.tools.idea.templates

**Comment by kevindesai777** [comment]
Yes, that's right. No problem. I will think of an alternative. Can I know when is the next version of the template releasing?

**Comment by kanytu** [comment]
So far I have no plans for a new update since I don't know what I can do to make it better.If you have any suggestion feel free to add an issue with it :)

**Comment by kevindesai777** [comment]
Not an issue, just a suggestion. Changing the icon on pressing in the navigation bar. Like the gray icon is replaced by the black version. Many would want this. I had difficulty in implementing it.

**Comment by kanytu** [comment]
I see, I've seen someone asking for the same thing on my blog I think. Yes that could be classified as "issue" since I will accept valid suggestions there :).  Will check it later in the day. It's quite easy to do.

**Pull request closed without merging**
